[package]
name = "kinqandi/dumpster"
version = "0.3.8"
registry = "https://github.com/UpliftGames/wally-index"
license = "MIT OR Apache-2.0"
realm = "shared"
authors = [
	"KinqAndi (https://github.com/KinqAndi)",
]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json"]
exclude = ["**"]